
server {
    listen 127.0.0.1:80;
    server_name
        js-blocker.com
        subdomain.js-blocker.com
        subdomain.subdomain.js-blocker.com
        js-blocker
        xn--js--dddu3aag1ax;
    root    /Volumes/dev/xcode/js_blocker/web-test/webroot;
    include /Volumes/dev/xcode/js_blocker/web-test/webroot/.nginx;
}

server {
    listen 127.0.0.1:443 ssl;
    server_name
        js-blocker.com
        subdomain.js-blocker.com
        subdomain.subdomain.js-blocker.com
        js-blocker
        xn--js--dddu3aag1ax;
    root    /Volumes/dev/xcode/js_blocker/web-test/webroot;
    include /Volumes/dev/xcode/js_blocker/web-test/webroot/.nginx;
    ssl_certificate     /Volumes/dev/web/sert/domain.crt;
    ssl_certificate_key /Volumes/dev/web/sert/domain.private.key;
}
